In [1]:
#import Pandas Library
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Assigned dataset variable to read insurance.csv file with the function of read_csv
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
#Convert Categorical data to nominal data (one hot encoding) and drop first categorical (State_California)
dataset=pd.get_dummies(dataset,drop_first=True).astype(int)

In [5]:
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [6]:
#Find column Headers
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
#Assign variable (independent) for only input data
independent=dataset[['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes']]

In [8]:
independent

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [9]:
#Assign variable for Output (dependent)
dependent=dataset[['charges']]

In [10]:
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {"criterion":["squared_error","absolute_error", "friedman_mse", "poisson"],
    "max_features":[None, "sqrt", "log2"],
    "splitter":["best", "random"]
}
grid = GridSearchCV(DecisionTreeRegressor(random_state=0), param_grid, cv=5, refit=True, verbose=3, n_jobs=-1, error_score="raise")
#fitting the model for grid search
grid.fit(independent, dependent)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

GridSearchCV(cv=5, error_score='raise',
             estimator=DecisionTreeRegressor(random_state=0), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [12]:
#print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_
print ("The R_Score value for best parameter {}:".format(grid.best_params_))

The R_Score value for best parameter {'criterion': 'squared_error', 'max_features': None, 'splitter': 'best'}:

In [13]:
table=pd.DataFrame.from_dict(re)

In [14]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.015291,0.001015,0.005656,0.000842,squared_error,None,best,"{'criterion': 'squared_error', 'max_features':...",0.999901,0.999966,0.999501,0.999570,0.999449,0.999678,0.000213,1
1,0.012867,0.001311,0.006469,0.000372,squared_error,None,random,"{'criterion': 'squared_error', 'max_features':...",0.998368,0.998264,0.996435,0.998835,0.992730,0.996926,0.002252,6
2,0.011619,0.001606,0.005040,0.001036,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.938666,0.917808,0.953739,0.976586,0.960474,0.949454,0.019969,21
3,0.010636,0.001762,0.005811,0.001042,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.968559,0.954848,0.966775,0.924342,0.956934,0.954292,0.015898,15
4,0.012811,0.002350,0.005935,0.001043,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.938666,0.917808,0.953739,0.976586,0.960474,0.949454,0.019969,21
5,0.009713,0.002834,0.004622,0.001199,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.968559,0.954848,0.966775,0.924342,0.956934,0.954292,0.015898,15
6,0.044429,0.010856,0.003523,0.001052,absolute_error,None,best,"{'criterion': 'absolute_error', 'max_features'...",0.999806,0.999720,0.997710,0.999573,0.997936,0.998949,0.000925,4
7,0.037556,0.002303,0.004830,0.000862,absolute_error,None,random,"{'criterion': 'absolute_error', 'max_features'...",0.995961,0.982032,0.998044,0.998486,0.980033,0.990911,0.008136,8
8,0.025954,0.001788,0.006010,0.001472,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.973147,0.965406,0.973631,0.952660,0.932267,0.959422,0.015551,9
9,0.025026,0.001961,0.005338,0.001498,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.958836,0.920128,0.982960,0.969415,0.935930,0.953454,0.022680,17
10,0.025487,0.002698,0.005031,0.001012,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.973147,0.965406,0.973631,0.952660,0.932267,0.959422,0.015551,9
11,0.025073,0.002941,0.004575,0.001099,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.958836,0.920128,0.982960,0.969415,0.935930,0.953454,0.022680,17
12,0.012220,0.000591,0.004058,0.000425,friedman_mse,None,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.999901,0.999966,0.999501,0.999570,0.999449,0.999678,0.000213,1
13,0.008805,0.001383,0.004131,0.000606,friedman_mse,None,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.998368,0.998264,0.996435,0.998835,0.992730,0.996926,0.002252,6
14,0.008500,0.000905,0.004127,0.000681,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.938666,0.914030,0.953739,0.976586,0.960474,0.948699,0.021186,23
15,0.007028,0.000838,0.003615,0.000289,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.968559,0.954848,0.966775,0.924342,0.949817,0.952868,0.015916,19
16,0.007423,0.001044,0.003680,0.000442,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.938666,0.914030,0.953739,0.976586,0.960474,0.948699,0.021186,23
17,0.007053,0.000278,0.003932,0.000217,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.968559,0.954848,0.966775,0.924342,0.949817,0.952868,0.015916,19
18,0.012126,0.000880,0.003805,0.000310,poisson,None,best,"{'criterion': 'poisson', 'max_features': None,...",0.999591,0.999736,0.999087,0.999561,0.999013,0.999397,0.000291,3
19,0.009355,0.000497,0.003903,0.000312,poisson,None,random,"{'criterion': 'poisson', 'max_features': None,...",0.999170,0.999070,0.995196,0.997684,0.996689,0.997562,0.001499,5
20,0.008820,0.000945,0.003591,0.000334,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.982311,0.929114,0.968600,0.932305,0.960863,0.954639,0.020735,13
21,0.006580,0.000828,0.003579,0.000292,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.963280,0.954848,0.981048,0.924342,0.949856,0.954675,0.018509,11
22,0.007438,0.000831,0.003332,0.000488,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.982311,0.929114,0.968600,0.932305,0.960863,0.954639,0.020735,13
23,0.006405,0.000318,0.002880,0.000637,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.963280,0.954848,0.981048,0.924342,0.949856,0.954675,0.018509,11

In [15]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male <0 or 1>:"))
sex_female_input=int(input("Sex Female <0 or 1>:"))
smoker_yes_input=int(input("Smoker Yes <0 or 1>:"))

Age: 32
BMI: 43
Children: 2
Sex Male <0 or 1>: 1
Sex Female <0 or 1>: 1
Smoker Yes <0 or 1>: 1

In [16]:
Future_Prediction = grid.predict([[age_input, bmi_input, children_input, sex_male_input, smoker_yes_input, sex_female_input]])
print("Future_Prediction={}".format(Future_Prediction))
print("Best Parameters:", grid.best_params_)
print("Best Score:", grid.best_score_)

Future_Prediction=[1146.]
Best Parameters: {'criterion': 'squared_error', 'max_features': None, 'splitter': 'best'}
Best Score: 0.9996775738365097

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(