In [1]:
#import Pandas Library
import pandas as pd

In [2]:
#Assigned dataset variable to read 50_Startups.csv file with the function of read_csv
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
#Convert Categorical data to nominal data (one hot encoding) and drop first categorical (State_California)
dataset=pd.get_dummies(dataset,drop_first=True).astype(int)

In [5]:
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [6]:
#Find column Headers
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [8]:
#Assign variable (independent) for only input data
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [9]:
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [10]:
#Assign variable for Output (dependent)
dependent=dataset[['charges']]

In [11]:
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [12]:
#Model Creation
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid = {"criterion":["squared_error","absolute_error", "friedman_mse", "poisson"],
    "max_features":[None, "sqrt", "log2"],
    "n_estimators":[10,100]
}
grid = GridSearchCV(RandomForestRegressor(), param_grid, cv=5, refit=True, verbose=3, n_jobs=-1, error_score="raise")
#fitting the model for grid search
grid.fit(independent, dependent)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(cv=5, error_score='raise', estimator=RandomForestRegressor(),
             n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [13]:
#print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_
print ("The R_Score value for best parameter {}:".format(grid.best_params_))

The R_Score value for best parameter {'criterion': 'absolute_error', 'max_features': 'log2', 'n_estimators': 100}:

In [14]:
table=pd.DataFrame.from_dict(re)

In [15]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.041809,0.000783,0.004722,0.000147,squared_error,None,10,"{'criterion': 'squared_error', 'max_features':...",0.823025,0.758093,0.851848,0.799168,0.824842,0.811395,0.031442,21
1,0.350558,0.008905,0.015510,0.000220,squared_error,None,100,"{'criterion': 'squared_error', 'max_features':...",0.842896,0.769236,0.854877,0.807938,0.830265,0.821042,0.030209,10
2,0.035929,0.000699,0.004713,0.000150,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.840567,0.754111,0.844655,0.804786,0.808857,0.810595,0.032513,22
3,0.277766,0.005375,0.015551,0.001092,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.851841,0.771497,0.850279,0.821945,0.836170,0.826346,0.029486,7
4,0.032173,0.001025,0.004545,0.000434,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.843619,0.756358,0.844963,0.797586,0.835658,0.815637,0.034304,15
5,0.267215,0.006384,0.016285,0.000762,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.852349,0.771310,0.858637,0.824796,0.835909,0.828600,0.031036,5
6,0.145623,0.002123,0.004113,0.000203,absolute_error,None,10,"{'criterion': 'absolute_error', 'max_features'...",0.817440,0.758268,0.857351,0.810226,0.827798,0.814216,0.032254,16
7,1.395589,0.029629,0.013965,0.000252,absolute_error,None,100,"{'criterion': 'absolute_error', 'max_features'...",0.837656,0.758174,0.858596,0.822091,0.836829,0.822669,0.034281,9
8,0.088819,0.002351,0.003596,0.000222,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.835697,0.752527,0.839594,0.803973,0.827201,0.811798,0.032110,20
9,0.826066,0.021089,0.013342,0.000425,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.856482,0.772163,0.850158,0.825910,0.843833,0.829709,0.030530,2
10,0.085354,0.003656,0.003632,0.000197,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.835049,0.766934,0.839475,0.804817,0.836448,0.816545,0.027796,14
11,0.825222,0.028592,0.014077,0.000875,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.854525,0.772563,0.854021,0.826213,0.841792,0.829823,0.030433,1
12,0.035919,0.001583,0.003826,0.000370,friedman_mse,None,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.818559,0.768372,0.845873,0.799874,0.808691,0.808274,0.025229,23
13,0.334344,0.004273,0.015137,0.000503,friedman_mse,None,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.839273,0.768182,0.852810,0.806656,0.830509,0.819486,0.029733,12
14,0.030436,0.000711,0.004204,0.000432,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.845035,0.747721,0.828045,0.807614,0.837158,0.813115,0.035004,17
15,0.265602,0.002165,0.014757,0.000697,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.850488,0.775610,0.843484,0.822937,0.836619,0.825827,0.026708,8
16,0.030589,0.001766,0.004003,0.000558,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.829392,0.751938,0.837384,0.817078,0.827221,0.812603,0.031016,18
17,0.266927,0.012192,0.013454,0.000295,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.855182,0.768951,0.852911,0.823538,0.837071,0.827531,0.031456,6
18,0.041505,0.001415,0.004662,0.000665,poisson,None,10,"{'criterion': 'poisson', 'max_features': None,...",0.849344,0.761378,0.848539,0.791686,0.811593,0.812508,0.033775,19
19,0.368322,0.005720,0.013537,0.000608,poisson,None,100,"{'criterion': 'poisson', 'max_features': None,...",0.844434,0.766881,0.855987,0.802724,0.828307,0.819667,0.031877,11
20,0.035169,0.000441,0.004523,0.000570,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.837476,0.772171,0.859896,0.806634,0.817203,0.818676,0.029538,13
21,0.296968,0.006746,0.013450,0.001015,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.855903,0.775682,0.855200,0.819840,0.838773,0.829080,0.029774,3
22,0.032390,0.001070,0.003881,0.000213,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.848602,0.752227,0.816688,0.794156,0.810589,0.804452,0.031528,24
23,0.258941,0.006263,0.010509,0.001510,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.854087,0.770111,0.858216,0.823467,0.838421,0.828861,0.031844,4

In [16]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male <0 or 1>:"))
smoker_yes_input=int(input("Smoker Yes <0 or 1>:"))

Age: 32
BMI: 43
Children: 2
Sex Male <0 or 1>: 1
Smoker Yes <0 or 1>: 1

In [17]:
Future_Prediction = grid.predict([[age_input, bmi_input, children_input, sex_male_input, smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))
print("Best Parameters:", grid.best_params_)
print("Best Score:", grid.best_score_)

Future_Prediction=[41476.785]
Best Parameters: {'criterion': 'absolute_error', 'max_features': 'log2', 'n_estimators': 100}
Best Score: 0.82982251647625

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(