In [22]:
#import Pandas Library
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [23]:
#Assigned dataset variable to read 50_Startups.csv file with the function of read_csv
dataset=pd.read_csv("insurance_pre.csv")

In [24]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [25]:
#Convert Categorical data to nominal data (one hot encoding) and drop first categorical (sex_male, smoker_yes)
dataset=pd.get_dummies(dataset,dtype=int, drop_first=True)

In [26]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [27]:
#Find column Headers
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [28]:
#Assign variable (independent) for only input data
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [29]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [30]:
#Assign variable for Output (dependent)
dependent=dataset['charges']

In [31]:
dependent

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [32]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {
    "kernel":["rbf", "poly", "sigmoid", "linear"],
    "C":[10,100,1000,2000,3000],
    "gamma":["scale"]
}
grid = GridSearchCV(SVR(), param_grid, cv=3, scoring="r2", verbose=3, n_jobs=-1)
#fitting the model for grid search
grid.fit(independent, dependent)

Fitting 3 folds for each of 20 candidates, totalling 60 fits

GridSearchCV(cv=3, estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000], 'gamma': ['scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             scoring='r2', verbose=3)

In [33]:
#print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_
print ("The R_Score value for best parameter {}:".format(grid.best_params_))

The R_Score value for best parameter {'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}:

In [34]:
table=pd.DataFrame.from_dict(re)

In [35]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.076101,0.003022,0.055803,0.001906,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.120647,-0.062407,-0.126932,-0.103329,0.029050,9
1,0.061581,0.005536,0.017917,0.001838,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",-0.117169,-0.084321,-0.180189,-0.127226,0.039778,11
2,0.071562,0.001949,0.025968,0.001053,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",-0.126045,-0.075274,-0.117573,-0.106297,0.022208,10
3,0.070689,0.006931,0.015639,0.000137,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",-0.029744,0.024305,-0.087219,-0.030886,0.045536,6
4,0.074804,0.002149,0.055257,0.002451,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",-0.147772,-0.094747,-0.201098,-0.147873,0.043418,17
5,0.064916,0.000448,0.016614,0.000799,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",-0.122152,-0.100605,-0.191723,-0.138160,0.038883,14
6,0.068279,0.004899,0.025393,0.000236,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",-0.151746,-0.103873,-0.138200,-0.131273,0.020148,13
7,0.115511,0.008619,0.016629,0.001307,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.535721,0.532197,0.486564,0.518161,0.022388,4
8,0.065528,0.005894,0.053770,0.002523,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",-0.141802,-0.098386,-0.202734,-0.147641,0.042799,16
9,0.069797,0.003379,0.016971,0.000132,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",-0.074574,-0.057414,-0.149167,-0.093719,0.039829,8
10,0.064058,0.000875,0.026333,0.000505,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",-1.636325,-1.642364,-1.478968,-1.585886,0.075642,18
11,0.351366,0.033712,0.014309,0.001244,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.674923,0.673021,0.642308,0.663417,0.014947,3
12,0.070071,0.008391,0.051661,0.001389,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",-0.131807,-0.091517,-0.195013,-0.139446,0.042596,15
13,0.081811,0.003442,0.016814,0.000421,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",-0.022469,-0.003566,-0.101774,-0.042603,0.042546,7
14,0.063890,0.000502,0.025760,0.000492,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-5.571911,-5.741249,-5.162330,-5.491830,0.243032,19
15,0.679950,0.195578,0.010089,0.003463,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.711945,0.735741,0.658711,0.702132,0.032204,1
16,0.069227,0.002257,0.048054,0.006087,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",-0.120606,-0.081697,-0.184108,-0.128804,0.042209,12
17,0.106760,0.005150,0.012626,0.002026,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.028404,0.049328,-0.055996,0.007245,0.045527,5
18,0.063805,0.001506,0.023759,0.001313,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-12.158574,-12.653723,-11.192128,-12.001475,0.606946,20
19,0.773161,0.079566,0.010663,0.003080,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.672138,0.713891,0.643214,0.676414,0.029012,2

In [36]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male <0 or 1>:"))
smoker_yes_input=int(input("Smoker Yes <0 or 1>:"))

Age: 32
BMI: 43
Children: 2
Sex Male <0 or 1>: 1
Smoker Yes <0 or 1>: 1

In [37]:
Future_Prediction = grid.predict([[age_input, bmi_input, children_input, sex_male_input, smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))
print("Best Parameters:", grid.best_params_)
print("Best Score:", grid.best_score_)

Future_Prediction=[36193.29454335]
Best Parameters: {'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}
Best Score: 0.7021323301015325

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(