In [1]:
#import Pandas Library
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
#Assigned dataset variable to read 50_Startups.csv file with the function of read_csv
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
#Convert Categorical data to nominal data (one hot encoding) and drop first categorical (sex_male, smoker_yes)
dataset=pd.get_dummies(dataset,dtype=int, drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
#Find column Headers
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
#Assign variable (independent) for only input data
independent=dataset[['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes']]

In [8]:
independent

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [9]:
#Assign variable for Output (dependent)
dependent=dataset['charges']

In [10]:
dependent

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {
    "kernel":["rbf", "poly", "sigmoid", "linear"],
    "C":[10,100,1000,2000,3000],
    "gamma":["scale"]
}
grid = GridSearchCV(SVR(), param_grid, cv=3, scoring="r2", verbose=3, n_jobs=-1)
#fitting the model for grid search
grid.fit(independent, dependent)

Fitting 3 folds for each of 20 candidates, totalling 60 fits

GridSearchCV(cv=3, estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000], 'gamma': ['scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             scoring='r2', verbose=3)

In [12]:
#print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_
print ("The R_Score value for best parameter {}:".format(grid.best_params_))

The R_Score value for best parameter {'C': 10, 'gamma': 'scale', 'kernel': 'linear'}:

In [13]:
table=pd.DataFrame.from_dict(re)

In [14]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.097025,0.004424,0.096127,0.005967,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.091889,0.136230,0.097108,0.108409,1.978780e-02,15
1,0.075951,0.001812,0.027267,0.000460,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.814823,0.727876,0.743844,0.762181,3.779011e-02,10
2,0.103252,0.002916,0.037891,0.001035,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",-0.085321,-0.032947,-0.077674,-0.065314,2.309882e-02,16
3,0.019921,0.017656,0.004490,0.000539,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",1.000000,1.000000,1.000000,1.000000,1.513053e-12,1
4,0.098440,0.003481,0.099435,0.001022,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.821769,0.814453,0.805857,0.814026,6.503063e-03,9
5,0.076515,0.003161,0.028563,0.001270,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.811246,0.706885,0.732667,0.750266,4.438533e-02,11
6,0.101763,0.002904,0.037275,0.000903,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",-0.304831,-0.232132,-0.293109,-0.276691,3.186908e-02,17
7,0.020539,0.019664,0.004957,0.001126,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",1.000000,1.000000,1.000000,1.000000,1.513053e-12,1
8,0.138312,0.001523,0.091082,0.005798,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.998703,0.981027,0.982048,0.987259,8.102383e-03,8
9,0.102775,0.000717,0.027333,0.000401,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.811292,0.706946,0.719291,0.745843,4.655323e-02,14
10,0.083995,0.018002,0.031721,0.007899,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",-15.726093,-13.937079,-15.550978,-15.071383,8.052541e-01,18
11,0.018246,0.018917,0.003434,0.000396,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",1.000000,1.000000,1.000000,1.000000,1.513053e-12,1
12,0.144149,0.004687,0.095492,0.000995,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.999829,0.988269,0.988964,0.992354,5.293063e-03,7
13,0.109754,0.005518,0.027685,0.001568,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.811346,0.707018,0.719439,0.745934,4.652988e-02,13
14,0.098091,0.001029,0.035954,0.000303,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-52.487076,-46.321725,-52.260047,-50.356283,2.854368e+00,19
15,0.016463,0.017275,0.003131,0.000216,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",1.000000,1.000000,1.000000,1.000000,1.513053e-12,1
16,0.165961,0.011567,0.048582,0.000904,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.999973,0.992237,0.992931,0.995047,3.494712e-03,6
17,0.108920,0.010744,0.015397,0.000526,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.811399,0.707091,0.719587,0.746026,4.650655e-02,12
18,0.087632,0.008723,0.027491,0.003690,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-110.213424,-97.874086,-109.944592,-106.010701,5.754502e+00,20
19,0.015024,0.014709,0.002911,0.000540,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",1.000000,1.000000,1.000000,1.000000,1.513053e-12,1

In [15]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male <0 or 1>:"))
sex_female_input=int(input("Sex Female <0 or 1>:"))
smoker_yes_input=int(input("Smoker Yes <0 or 1>:"))

Age: 35
BMI: 43
Children: 2
Sex Male <0 or 1>: 1
Sex Female <0 or 1>: 1
Smoker Yes <0 or 1>: 1

In [17]:
Future_Prediction = grid.predict([[age_input, bmi_input, children_input, sex_male_input, smoker_yes_input, sex_female_input]])
print("Future_Prediction={}".format(Future_Prediction))
print("Best Parameters:", grid.best_params_)
print("Best Score:", grid.best_score_)

Future_Prediction=[1.11181231]
Best Parameters: {'C': 10, 'gamma': 'scale', 'kernel': 'linear'}
Best Score: 0.9999999999578332

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(